extraction:
  cpp:
    prepare:
      packages:
        - libgmp-dev
        - libboost-graph-dev
        - libboost-iostreams-dev
        - zlib1g-dev
        - liblzma-dev
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DMPI=OFF ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make 
  python:
    python_setup:
      version: 3
