language: cpp
compiler: clang
dist: trusty

addons:
  apt:
    packages: libboost-graph-dev libboost-iostreams-dev libgmp-dev zlib1g-dev liblzma-dev libjemalloc-dev libopenmpi-dev openmpi-bin

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
